name: "Hello Actions"
description: "Greet Someone"
author: "virgoaugustine@gmail.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"
  
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"